### ISSUE TITLE
Comparison of pyarrowfs-adlgen2 with adlfs

### ISSUE THREAD

**Issue by th0ger** [kaaveland/pyarrowfs-adlgen2#16]
I'm curious to know how  `pyarrowfs-adlgen2` compares to (the more community-backed) `adlfs`.

Is `pyarrowfs-adlgen2` trying to obtain the same goal, or is there a different design pattern behind this?

> `pyarrowfs-adlgen2` is an implementation of a pyarrow filesystem for Azure Data Lake Gen2.
>
> [fsspec/adlfs](https://github.com/fsspec/adlfs) Filesystem interface to Azure-Datalake Gen1 and Gen2 Storage

I'm using `adlfs` with success.

**Comment by kaaveland** [comment]
The important differences are:

- I do not implement fsspec, which has a fairly big API surface. I do not need the extra functionality, I only need arrow to work.
- I focus only on data lake gen2. I know that it still works with blob storage accounts, but that's a happy accident.

At the time I wrote the first implementation, the fsspec one had terrible performance on data lake gen2 for data sets with many files, which was my primary usecase. I could not easily see how to improve the performance of the fsspec based solution. I would not be surprised if pyarrowfs-adlgen2 is still faster for those cases, but I haven't tested for a very long time. 

Had a quick look at the dependencies, and it still does not use azure-storage-file-datalake, which is the data lake gen2 SDK, so I think it must still be using the blobstorage API under the hood. That one does not support real directory structure, so listing directory contents is based on blob prefix matching, which is slow. Or, that was the case a year back, at least.

**Comment by th0ger** [comment]
@kaaveland thanks for the writeup, that's really helpful!

> At the time I wrote the first implementation, the fsspec one had terrible performance on data lake gen2 for data sets with many files, which was my primary usecase. I could not easily see how to improve the performance of the fsspec based solution. I would not be surprised if pyarrowfs-adlgen2 is still faster for those cases, but I haven't tested for a very long time.

Okay, if performance is the primary (and only) target of `pyarrowfs-adlgen2`, then I think this repo should keep updated benchmarks against `adlfs`. Otherwise each potential user would have to build their own benchmark before knowing which library to select.

> Had a quick look at the dependencies, and it still does not use azure-storage-file-datalake, which is the data lake gen2 SDK, so I think it must still be using the blobstorage API under the hood. That one does not support real directory structure, so listing directory contents is based on blob prefix matching, which is slow. Or, that was the case a year back, at least.

Do you know if the `adlfs` project is aware of the performance issues and/or have considered to move from the blobstorage API to `azure-storage-file-datalake` for ADLS Gen2 cases?

**Comment by kaaveland** [comment]
> Okay, if performance is the primary (and only) target of pyarrowfs-adlgen2, then I think this repo should keep updated benchmarks against adlfs. Otherwise each potential user would have to build their own benchmark before knowing which library to select.

I would be happy to accept benchmark code from somebody else, but I am *probably* not going to spend my spare time on writing that anytime soon. :-) I guess we would need a public azure storage account with a lot of files in it to have a benchmark at all, if you know of any good candidates I might consider making something at some point?

Performance was what spurred me into writing this, but a second goal was to have a smaller/more minimal library for the narrower use case I had. In my experience, the number of bugs in a project correlates almost linearly with the amount of code, and `adlfs` has a lot of functionality that I don't need. It also needs to stay consistent with other fsspec implementations such as s3 and gcs. This would also make it hard for them to implement fine-grained timeouts and functionality like setting content-type in a uniform manner. These reasons also made me believe that there was a place for a project with a narrower scope.

If you *do need* data lake gen1, async, work primarily with blob storage, or require fsspec, I would definitely go for `adlfs` regardless.

> Do you know if the adlfs project is aware of the performance issues and/or have considered to move from the blobstorage API to azure-storage-file-datalake for ADLS Gen2 cases?

No, I don't know. I do know that they have resolved several performance issues in their tracker, so those problems might be gone now. I considered offering to implement azure-storage-file-datalake for them, but I chickened out when I was writing the issue because it would take quite a lot of discussion to get a thing like that going anyway and I wasn't sure if I could implement fsspec correctly.

**Comment by kaaveland** [comment]
We're talking about things that happened a long time ago now, but I think the authentication mechanisms in `adlfs` might've also been one of the reasons I did this. I wanted to use `DefaultAzureCredential` with data access, so that I could use my own AAD user when developing/testing locally, and run with managed identity or service principals in unattended pipelines without code changes and I don't think `adlfs` had support for `azure-identity` at the time (although that might've changed too).
