### ISSUE TITLE
Does PyArrowFS_ADLGen2 support using a connection string to connect to the storage account?

### ISSUE THREAD

**Issue by javiermtl** [kaaveland/pyarrowfs-adlgen2#19]
Does PyArrowFS_ADLGen2 support using a connection string to connect to the storage account?

**Comment by kaaveland** [comment]
As long as you can create an instance of either https://learn.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.filesystemclient?view=azure-python or https://learn.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.filesystemclient?view=azure-python you should be good, you'll use the constructor for either `FileSystemHandler` or `AccountHandler` instead of the `from_account_name`-constructors.

If the azure sdk classes I linked do not support connection strings, you're out of luck.
