### ISSUE TITLE
pyarrowfs_adlgen2.FilesystemHandler.from_account_name does not work with dataset

### ISSUE THREAD

**Issue by dev1010101** [kaaveland/pyarrowfs-adlgen2#9]
**Example**
handler = pyarrowfs_adlgen2.FilesystemHandler.from_account_name('<account_name>','<file_system_name>',cred)
fs = pyarrow.fs.PyFileSystem(handler)
ds = pyarrow.dataset.dataset('folderBase', filesystem=fs)
**Error:**
ArrowInvalid: GetFileInfo() yielded path '<file_system_name>/folderBase/folder/file.parquet', which is outside base dir 'folderBase'

**Notes:**
I can not use AccountHandler.from_account_name because of permissions (but assume that would work if I had them)

If you do specify a specific file with the container as first path it does not work
ResourceNotFoundError: (PathNotFound) The specified path does not exist.

If you specify a list of files it does work.

**Comment by kaaveland** [comment]
The issue is this line: https://github.com/kaaveland/pyarrowfs-adlgen2/blob/master/pyarrowfs_adlgen2/core.py#L319

It is passing `timeouts` for `prefix_fs`, it should use named parameters invoking that init.

I will see if I can release a fix tomorrow morning - feel free to make a pull request if you can get to it before that. Otherwise you should be able to work around the issue by creating an instance of the class directly, until this is fixed

**Comment by dev1010101** [comment]
Thx for the quick response. That is indeed a trivial fix. No need to hurry, I figured out that in my current case I can work around it by providing a fixed file list to the dataset constructor.

**Comment by kaaveland** [comment]
Released https://github.com/kaaveland/pyarrowfs-adlgen2/pull/10 in https://pypi.org/project/pyarrowfs-adlgen2/0.2.1/ now, which should take care of this. Thanks for the report!
